### ISSUE TITLE
render pass not working / warning X3595

### ISSUE THREAD

**Issue by noname0310** [Ameobea/three-good-godrays#5]
I got error on three.js r146 (latest), need help

```
THREE.WebGLProgram: Program Info Log: C:\fakepath(89,12-86): warning X3595: gradient instruction used in a loop with varying iteration; partial derivatives may have undefined value
```

**Comment by Ameobea** [comment]
Hi, thanks for the report.  Could you tell me some info about your system and scenario?

 * What browser and operating system are you using?  What kind of GPU do you have?
 * Are you running any other Three.JS/WebGL code along with this effect?
 * Are you using the bilateral blur pass feature of the godrays shader?

**Comment by noname0310** [comment]
I ran it on the Nvidia GPU and the Intel integrated graphics card
- I tried running it on edge and firefox.
- The same error occurred when I removed all the objects in the scene and tried using only this pass to check the problem.
- I don't know about bilateral blur pass

**Comment by noname0310** [comment]
https://github.com/noname0310/three-good-godrays-test Code reproducing the problem. There is a problem even if you use the code on the readme as it is.

https://github.com/noname0310/web-mmd-viewer And this is a project that I'm applying three-good-godrays.

**Comment by Ameobea** [comment]
Do the demos on the demo site work for you? https://three-good-godrays.ameo.design/#dirlight

I'm curious as to whether this is just a warning or if it actually prevents the godrays from working in this scenario.  If the demos work, then there's probably some configuration issue with the code you're using and we can explore that from there.

However, if the demos do not work for you, then I will need to investigate alternative solutions for the godrays implementation.

**Comment by noname0310** [comment]
It's working, I think I was using it wrong.

But even in the demo, there's a warning on the console

**Comment by noname0310** [comment]
I'm not sure if I'm using it wrong or if this render pass is the way it is.

![1](https://user-images.githubusercontent.com/48761044/204082117-5cc12879-266c-4389-9157-d9f1f18cfdef.png)
When you look at the floor, I can see Godray like a shadow.

![2](https://user-images.githubusercontent.com/48761044/204082218-dec54e92-6dfd-4ff8-98e5-1313f5aeeac6.png)
But from this angle, it's completely invisible.

I wonder if this render pass can't make a godray that feels similar to volumetric fog. When I looked at the demo, it seemed like it was possible.

**Comment by Ameobea** [comment]
What type of light are you using in the project?  If you're using a directional light, you may need to tweak some of the shadow settings like the light's camera's near/far as well as right/left/top/bottom params to get it to look alright.

Also will be important to tweak the params for the effect itself to match your scene; especially look into the `density` and `distanceAttenuation` params.

If you're still having trouble getting it to look decent, if you push up the code you're working with currently I can take a look and see if I can get it to work myself

**Comment by noname0310** [comment]
Thank you for your kind reply. I will try and open the issue again if there is a problem.
