### ISSUE TITLE
Effect only visible at specific angles outside of the shadow box

### ISSUE THREAD

**Issue by chrisrogers3d** [Ameobea/three-good-godrays#6]
hey, cool, thanks for sharing.
the demos all work for me
im trying to put it in to my project, and after many hours i found the depthtexture was not being created as it was in the dirlight demo.
so i added one myself and a part of the effect (looks like height fog upside down, but no streaks of shadow) looks correct only at certain angles (perpendicular to plane of shadow box) outside of the shadowbox.
![image](https://user-images.githubusercontent.com/10109103/232336950-2e77a15d-c92f-4756-8d69-b614690e49d6.png)
![image](https://user-images.githubusercontent.com/10109103/232336987-4cb4b762-0e5e-415e-993c-bf4ab4215266.png)

edit:  at one point i was able to get shadow streaks, they seemed to appear only on the plane of the shadow box edge, i cant get back to that point, :-(
![image](https://user-images.githubusercontent.com/10109103/232337116-168a1d85-fcde-4bd1-a146-f6677d0dfca7.png)

any sugggestions?

**Comment by Ameobea** [comment]
Hi, I'm not sure what's going wrong with your use case.  There are a lot of variables involved with this for sure and it can be tricky to get the effect working and looking good.

If you have your code available somewhere, I can take a look at that.  I'm afraid there's not a lot I can do given what I know currently, though.
